import { Pool, PoolConfig } from 'pg';
import dotenv from 'dotenv';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, '..', '.env.local') });

const PG_CONFIG: PoolConfig = {
  host: process.env.PG_HOST ?? 'localhost',
  port: Number(process.env.PG_PORT) || 5432,
  database: process.env.PG_DATABASE ?? 'hireflow',
  user: process.env.PG_USER ?? 'hireflow',
  password: process.env.PG_PASSWORD ?? '',
  ssl: process.env.PG_SSL === 'false' ? false : { rejectUnauthorized: false },
};

const pool = new Pool(PG_CONFIG);

type Stage =
  | 'screening'
  | 'shortlisted'
  | 'ai_interview'
  | 'in_person_interview'
  | 'hired'
  | 'rejected';

interface SeedCandidate {
  candidate_name: string;
  email: string;
  phone: string;
  source: 'form' | 'email';
  position: string;
  years_of_exp: number;
  linkedin: string;
  current_job_title: string;
  highest_degree: string;
  certifications: string;
  frontend_skills: string;
  frontend_level: string;
  backend_skills: string;
  backend_level: string;
  database_skills: string;
  database_level: string;
  ai_ml_skills: string;
  ai_ml_level: string;
  cloud_devops: string;
  programming_langs: string;
  notable_projects: string;
  jd_title: string;
  jd_company: string;
  total_score: number;
  frontend_score: number;
  backend_score: number;
  database_score: number;
  ai_ml_score: number;
  exp_score: number;
  soft_score: number;
  grade: string;
  recommendation: string;
  is_qualified: boolean;
  summary: string;
  strengths: string;
  weaknesses: string;
  frontend_feedback: string;
  backend_feedback: string;
  database_feedback: string;
  ai_ml_feedback: string;
  hiring_note: string;
  pipeline_stage: Stage;
  latest_stage_note: string;
  submitted_at: string;
  processed_at: string;
  pipeline_stage_updated_at: string;
  city: string | null;
}

const candidates: SeedCandidate[] = [
  {
    candidate_name: 'Aarav Mehta',
    email: 'aarav.mehta.seed@hireflow.test',
    phone: '+91 9876500001',
    source: 'email',
    position: 'Frontend Engineer',
    years_of_exp: 3,
    linkedin: 'linkedin.com/in/aaravmehta',
    current_job_title: 'Frontend Developer',
    highest_degree: 'B.Tech Computer Science',
    certifications: 'React Advanced, UI Performance',
    frontend_skills: 'React, TypeScript, Tailwind CSS, Next.js',
    frontend_level: 'advanced',
    backend_skills: 'Node.js, Express',
    backend_level: 'intermediate',
    database_skills: 'PostgreSQL',
    database_level: 'intermediate',
    ai_ml_skills: 'N/A',
    ai_ml_level: 'beginner',
    cloud_devops: 'Vercel, GitHub Actions',
    programming_langs: 'TypeScript, JavaScript',
    notable_projects: 'Design system revamp, analytics dashboard',
    jd_title: 'Frontend Engineer',
    jd_company: 'HireFlow',
    total_score: 88,
    frontend_score: 24,
    backend_score: 19,
    database_score: 13,
    ai_ml_score: 7,
    exp_score: 8,
    soft_score: 5,
    grade: 'A',
    recommendation: 'Strong Hire',
    is_qualified: true,
    summary: 'Strong frontend candidate with clean product thinking and solid TypeScript depth.',
    strengths: 'React architecture|UI polish|Performance mindset',
    weaknesses: 'Limited AI experience|Needs deeper system design exposure',
    frontend_feedback: 'Very strong React and modern UI delivery.',
    backend_feedback: 'Good API consumption and basic service experience.',
    database_feedback: 'Comfortable with SQL fundamentals.',
    ai_ml_feedback: 'No meaningful AI/ML signal in resume.',
    hiring_note: 'Great fit for product-facing frontend work.',
    pipeline_stage: 'shortlisted',
    latest_stage_note: 'Shortlisted by HR for strong UI portfolio.',
    submitted_at: '2026-06-14T10:00:00.000Z',
    processed_at: '2026-06-14T10:20:00.000Z',
    pipeline_stage_updated_at: '2026-06-16T09:00:00.000Z',
    city: 'Mumbai',
  },
  {
    candidate_name: 'Diya Sharma',
    email: 'diya.sharma.seed@hireflow.test',
    phone: '+91 9876500002',
    source: 'form',
    position: 'Backend Engineer',
    years_of_exp: 4,
    linkedin: 'linkedin.com/in/diyasharma',
    current_job_title: 'Software Engineer',
    highest_degree: 'B.E. Information Technology',
    certifications: 'Distributed Systems, AWS Developer',
    frontend_skills: 'React',
    frontend_level: 'beginner',
    backend_skills: 'Node.js, NestJS, Kafka, Redis',
    backend_level: 'expert',
    database_skills: 'PostgreSQL, MongoDB',
    database_level: 'advanced',
    ai_ml_skills: 'N/A',
    ai_ml_level: 'beginner',
    cloud_devops: 'AWS, Docker, Terraform',
    programming_langs: 'TypeScript, Go',
    notable_projects: 'Payment orchestration, event driven order service',
    jd_title: 'Backend Engineer',
    jd_company: 'HireFlow',
    total_score: 91,
    frontend_score: 12,
    backend_score: 25,
    database_score: 18,
    ai_ml_score: 5,
    exp_score: 10,
    soft_score: 5,
    grade: 'A+',
    recommendation: 'Strong Hire',
    is_qualified: true,
    summary: 'Excellent backend profile with ownership of production microservices.',
    strengths: 'Backend depth|Scalability|Cloud operations',
    weaknesses: 'Frontend depth is limited',
    frontend_feedback: 'Enough exposure for collaboration, not implementation heavy.',
    backend_feedback: 'Outstanding service design and reliability ownership.',
    database_feedback: 'Strong schema and query tuning signal.',
    ai_ml_feedback: 'Minimal AI overlap.',
    hiring_note: 'Prioritize for backend interview loop.',
    pipeline_stage: 'ai_interview',
    latest_stage_note: 'Moved into AI interview after strong technical screen.',
    submitted_at: '2026-06-11T08:45:00.000Z',
    processed_at: '2026-06-11T09:05:00.000Z',
    pipeline_stage_updated_at: '2026-06-18T13:30:00.000Z',
    city: 'Bangalore',
  },
  {
    candidate_name: 'Rahul Verma',
    email: 'rahul.verma.seed@hireflow.test',
    phone: '+91 9876500003',
    source: 'email',
    position: 'Full Stack Engineer',
    years_of_exp: 5,
    linkedin: 'linkedin.com/in/rahulverma',
    current_job_title: 'Senior Software Engineer',
    highest_degree: 'B.Tech Computer Science',
    certifications: 'AWS Solutions Architect',
    frontend_skills: 'React, Next.js, CSS',
    frontend_level: 'advanced',
    backend_skills: 'Node.js, GraphQL, Express',
    backend_level: 'advanced',
    database_skills: 'PostgreSQL, Redis',
    database_level: 'advanced',
    ai_ml_skills: 'OpenAI APIs, embeddings',
    ai_ml_level: 'intermediate',
    cloud_devops: 'AWS, Docker, CI/CD',
    programming_langs: 'TypeScript, Python',
    notable_projects: 'Internal copilot, applicant tracking rewrite',
    jd_title: 'Full Stack Engineer',
    jd_company: 'HireFlow',
    total_score: 94,
    frontend_score: 23,
    backend_score: 24,
    database_score: 17,
    ai_ml_score: 12,
    exp_score: 10,
    soft_score: 5,
    grade: 'A+',
    recommendation: 'Strong Hire',
    is_qualified: true,
    summary: 'Very balanced full stack candidate with relevant AI product work.',
    strengths: 'End-to-end ownership|AI integration|Shipping speed',
    weaknesses: 'Could show deeper ML fundamentals',
    frontend_feedback: 'Strong user-facing implementation skills.',
    backend_feedback: 'Good API design and delivery pace.',
    database_feedback: 'Solid operational database experience.',
    ai_ml_feedback: 'Applied AI experience is directly relevant.',
    hiring_note: 'Excellent all-rounder for priority role.',
    pipeline_stage: 'in_person_interview',
    latest_stage_note: 'Advanced to final in-person interview.',
    submitted_at: '2026-06-08T11:30:00.000Z',
    processed_at: '2026-06-08T11:50:00.000Z',
    pipeline_stage_updated_at: '2026-06-23T10:00:00.000Z',
    city: 'Delhi',
  },
  {
    candidate_name: 'Sneha Kulkarni',
    email: 'sneha.kulkarni.seed@hireflow.test',
    phone: '+91 9876500004',
    source: 'form',
    position: 'AI Engineer',
    years_of_exp: 3,
    linkedin: 'linkedin.com/in/snehakulkarni',
    current_job_title: 'ML Engineer',
    highest_degree: 'M.Tech AI',
    certifications: 'Deep Learning Specialization',
    frontend_skills: 'Streamlit',
    frontend_level: 'beginner',
    backend_skills: 'Python, FastAPI',
    backend_level: 'advanced',
    database_skills: 'PostgreSQL, Vector DB',
    database_level: 'intermediate',
    ai_ml_skills: 'LLMs, RAG, fine-tuning, prompt engineering',
    ai_ml_level: 'expert',
    cloud_devops: 'AWS, Docker',
    programming_langs: 'Python, SQL',
    notable_projects: 'RAG evaluator, support assistant',
    jd_title: 'AI Engineer',
    jd_company: 'HireFlow',
    total_score: 89,
    frontend_score: 8,
    backend_score: 20,
    database_score: 14,
    ai_ml_score: 15,
    exp_score: 10,
    soft_score: 5,
    grade: 'A',
    recommendation: 'Hire',
    is_qualified: true,
    summary: 'Strong applied AI profile with practical LLM deployment work.',
    strengths: 'LLM systems|Experimentation|Python APIs',
    weaknesses: 'Frontend experience limited',
    frontend_feedback: 'Frontend is enough for demos, not product UI.',
    backend_feedback: 'Strong service implementation in Python.',
    database_feedback: 'Capable with vector workflows and SQL basics.',
    ai_ml_feedback: 'Excellent fit for AI workflows and evaluation.',
    hiring_note: 'Good candidate for AI interview track.',
    pipeline_stage: 'screening',
    latest_stage_note: 'Awaiting recruiter shortlist decision.',
    submitted_at: '2026-06-17T07:45:00.000Z',
    processed_at: '2026-06-17T08:15:00.000Z',
    pipeline_stage_updated_at: '2026-06-17T08:15:00.000Z',
    city: 'Pune',
  },
  {
    candidate_name: 'Karan Patel',
    email: 'karan.patel.seed@hireflow.test',
    phone: '+91 9876500005',
    source: 'email',
    position: 'Data Analyst',
    years_of_exp: 2,
    linkedin: 'linkedin.com/in/karanpatel',
    current_job_title: 'Business Analyst',
    highest_degree: 'B.Sc Statistics',
    certifications: 'Power BI, SQL Analytics',
    frontend_skills: 'N/A',
    frontend_level: 'beginner',
    backend_skills: 'Python',
    backend_level: 'beginner',
    database_skills: 'SQL, BigQuery',
    database_level: 'advanced',
    ai_ml_skills: 'N/A',
    ai_ml_level: 'beginner',
    cloud_devops: 'N/A',
    programming_langs: 'SQL, Python',
    notable_projects: 'Sales forecasting dashboard',
    jd_title: 'Data Analyst',
    jd_company: 'HireFlow',
    total_score: 72,
    frontend_score: 2,
    backend_score: 8,
    database_score: 20,
    ai_ml_score: 3,
    exp_score: 6,
    soft_score: 4,
    grade: 'B',
    recommendation: 'Consider',
    is_qualified: true,
    summary: 'Analytical profile with good SQL grounding but less product engineering depth.',
    strengths: 'SQL reporting|Dashboarding|Stakeholder communication',
    weaknesses: 'Not a strong engineering fit|Limited backend depth',
    frontend_feedback: 'No product frontend signal.',
    backend_feedback: 'Basic scripting only.',
    database_feedback: 'Strong analytical SQL usage.',
    ai_ml_feedback: 'No AI depth.',
    hiring_note: 'Keep for analytics role, not engineering role.',
    pipeline_stage: 'screening',
    latest_stage_note: 'Role under review for analytics opening.',
    submitted_at: '2026-06-19T09:20:00.000Z',
    processed_at: '2026-06-19T09:40:00.000Z',
    pipeline_stage_updated_at: '2026-06-19T09:40:00.000Z',
    city: 'Ahmedabad',
  },
  {
    candidate_name: 'Nisha Iyer',
    email: 'nisha.iyer.seed@hireflow.test',
    phone: '+91 9876500006',
    source: 'form',
    position: 'Product Designer',
    years_of_exp: 4,
    linkedin: 'linkedin.com/in/nishaiyer',
    current_job_title: 'Product Designer',
    highest_degree: 'B.Des',
    certifications: 'UX Research, Design Systems',
    frontend_skills: 'Figma, HTML, CSS',
    frontend_level: 'intermediate',
    backend_skills: 'N/A',
    backend_level: 'beginner',
    database_skills: 'N/A',
    database_level: 'beginner',
    ai_ml_skills: 'AI prototyping tools',
    ai_ml_level: 'beginner',
    cloud_devops: 'N/A',
    programming_langs: 'N/A',
    notable_projects: 'B2B workflow redesign, mobile onboarding optimization',
    jd_title: 'Product Designer',
    jd_company: 'HireFlow',
    total_score: 83,
    frontend_score: 18,
    backend_score: 3,
    database_score: 1,
    ai_ml_score: 5,
    exp_score: 10,
    soft_score: 5,
    grade: 'A',
    recommendation: 'Hire',
    is_qualified: true,
    summary: 'Strong product design profile with systems thinking and collaboration maturity.',
    strengths: 'Design systems|User research|Cross-functional communication',
    weaknesses: 'Not a code-heavy profile',
    frontend_feedback: 'Good enough for collaboration with frontend teams.',
    backend_feedback: 'Not applicable.',
    database_feedback: 'Not applicable.',
    ai_ml_feedback: 'Uses AI tools for prototyping only.',
    hiring_note: 'Potential fit for design hiring stream.',
    pipeline_stage: 'ai_interview',
    latest_stage_note: 'Portfolio and async design task requested.',
    submitted_at: '2026-06-12T06:55:00.000Z',
    processed_at: '2026-06-12T07:15:00.000Z',
    pipeline_stage_updated_at: '2026-06-20T12:45:00.000Z',
    city: 'Chennai',
  },
  {
    candidate_name: 'Manav Singh',
    email: 'manav.singh.seed@hireflow.test',
    phone: '+91 9876500007',
    source: 'email',
    position: 'DevOps Engineer',
    years_of_exp: 6,
    linkedin: 'linkedin.com/in/manavsingh',
    current_job_title: 'Site Reliability Engineer',
    highest_degree: 'B.Tech Electronics',
    certifications: 'CKA, AWS SysOps',
    frontend_skills: 'N/A',
    frontend_level: 'beginner',
    backend_skills: 'Go, Bash, Python',
    backend_level: 'advanced',
    database_skills: 'PostgreSQL, MySQL',
    database_level: 'intermediate',
    ai_ml_skills: 'N/A',
    ai_ml_level: 'beginner',
    cloud_devops: 'Kubernetes, Terraform, AWS, Prometheus',
    programming_langs: 'Go, Python, Bash',
    notable_projects: 'Platform observability stack, cluster automation',
    jd_title: 'DevOps Engineer',
    jd_company: 'HireFlow',
    total_score: 86,
    frontend_score: 1,
    backend_score: 18,
    database_score: 10,
    ai_ml_score: 2,
    exp_score: 10,
    soft_score: 5,
    grade: 'A',
    recommendation: 'Hire',
    is_qualified: true,
    summary: 'Reliable infrastructure candidate with strong cloud and Kubernetes operations.',
    strengths: 'Kubernetes|Infra automation|Incident management',
    weaknesses: 'Not a frontend or product candidate',
    frontend_feedback: 'Not relevant.',
    backend_feedback: 'Solid scripting and platform engineering.',
    database_feedback: 'Enough for operational support.',
    ai_ml_feedback: 'No AI signal.',
    hiring_note: 'Good match for DevOps requirement.',
    pipeline_stage: 'hired',
    latest_stage_note: 'Offer accepted.',
    submitted_at: '2026-05-28T08:05:00.000Z',
    processed_at: '2026-05-28T08:30:00.000Z',
    pipeline_stage_updated_at: '2026-06-25T15:00:00.000Z',
    city: 'Hyderabad',
  },
  {
    candidate_name: 'Pooja Nair',
    email: 'pooja.nair.seed@hireflow.test',
    phone: '+91 9876500008',
    source: 'form',
    position: 'QA Engineer',
    years_of_exp: 3,
    linkedin: 'linkedin.com/in/poojanair',
    current_job_title: 'QA Automation Engineer',
    highest_degree: 'B.Tech IT',
    certifications: 'Selenium, Playwright',
    frontend_skills: 'Playwright',
    frontend_level: 'intermediate',
    backend_skills: 'Node.js',
    backend_level: 'beginner',
    database_skills: 'PostgreSQL',
    database_level: 'beginner',
    ai_ml_skills: 'N/A',
    ai_ml_level: 'beginner',
    cloud_devops: 'GitHub Actions',
    programming_langs: 'JavaScript',
    notable_projects: 'Regression automation, checkout flow test suite',
    jd_title: 'QA Engineer',
    jd_company: 'HireFlow',
    total_score: 76,
    frontend_score: 14,
    backend_score: 7,
    database_score: 8,
    ai_ml_score: 2,
    exp_score: 10,
    soft_score: 5,
    grade: 'B+',
    recommendation: 'Hire',
    is_qualified: true,
    summary: 'Good QA automation candidate with product workflow awareness.',
    strengths: 'Automation mindset|Test coverage|Cross-team coordination',
    weaknesses: 'Not strong for software engineering role',
    frontend_feedback: 'Good for end-to-end automation tasks.',
    backend_feedback: 'Basic scripting only.',
    database_feedback: 'Can validate data but not design schemas.',
    ai_ml_feedback: 'No AI depth.',
    hiring_note: 'Keep in QA funnel.',
    pipeline_stage: 'shortlisted',
    latest_stage_note: 'Shortlisted for QA panel discussion.',
    submitted_at: '2026-06-10T05:25:00.000Z',
    processed_at: '2026-06-10T05:50:00.000Z',
    pipeline_stage_updated_at: '2026-06-21T09:15:00.000Z',
    city: 'Kochi',
  },
  {
    candidate_name: 'Yash Agarwal',
    email: 'yash.agarwal.seed@hireflow.test',
    phone: '+91 9876500009',
    source: 'email',
    position: 'Backend Intern',
    years_of_exp: 1,
    linkedin: 'linkedin.com/in/yashagarwal',
    current_job_title: 'Student Developer',
    highest_degree: 'B.Tech Final Year',
    certifications: 'Java DSA',
    frontend_skills: 'HTML, CSS',
    frontend_level: 'beginner',
    backend_skills: 'Java, Spring Boot',
    backend_level: 'intermediate',
    database_skills: 'MySQL',
    database_level: 'intermediate',
    ai_ml_skills: 'N/A',
    ai_ml_level: 'beginner',
    cloud_devops: 'Render',
    programming_langs: 'Java',
    notable_projects: 'College placement portal',
    jd_title: 'Backend Intern',
    jd_company: 'HireFlow',
    total_score: 67,
    frontend_score: 5,
    backend_score: 17,
    database_score: 12,
    ai_ml_score: 1,
    exp_score: 7,
    soft_score: 4,
    grade: 'B',
    recommendation: 'Consider',
    is_qualified: true,
    summary: 'Promising junior backend candidate with decent fundamentals.',
    strengths: 'Java basics|Project ownership|Learning velocity',
    weaknesses: 'Limited real-world experience',
    frontend_feedback: 'Basic only.',
    backend_feedback: 'Good junior-level backend signal.',
    database_feedback: 'Comfortable with CRUD and joins.',
    ai_ml_feedback: 'No AI exposure.',
    hiring_note: 'Could work for internship track.',
    pipeline_stage: 'screening',
    latest_stage_note: 'Awaiting intern shortlist review.',
    submitted_at: '2026-06-22T10:10:00.000Z',
    processed_at: '2026-06-22T10:30:00.000Z',
    pipeline_stage_updated_at: '2026-06-22T10:30:00.000Z',
    city: 'Kolkata',
  },
  {
    candidate_name: 'Fatima Khan',
    email: 'fatima.khan.seed@hireflow.test',
    phone: '+91 9876500010',
    source: 'form',
    position: 'Customer Success Manager',
    years_of_exp: 5,
    linkedin: 'linkedin.com/in/fatimakhan',
    current_job_title: 'Customer Success Lead',
    highest_degree: 'MBA',
    certifications: 'SaaS Retention Strategy',
    frontend_skills: 'N/A',
    frontend_level: 'beginner',
    backend_skills: 'N/A',
    backend_level: 'beginner',
    database_skills: 'N/A',
    database_level: 'beginner',
    ai_ml_skills: 'N/A',
    ai_ml_level: 'beginner',
    cloud_devops: 'N/A',
    programming_langs: 'N/A',
    notable_projects: 'Onboarding playbook, renewal operations',
    jd_title: 'Customer Success Manager',
    jd_company: 'HireFlow',
    total_score: 79,
    frontend_score: 0,
    backend_score: 0,
    database_score: 0,
    ai_ml_score: 0,
    exp_score: 10,
    soft_score: 5,
    grade: 'B+',
    recommendation: 'Hire',
    is_qualified: true,
    summary: 'Strong customer-facing operator with SaaS retention experience.',
    strengths: 'Communication|Process ownership|Retention mindset',
    weaknesses: 'Not relevant for technical engineering openings',
    frontend_feedback: 'Not applicable.',
    backend_feedback: 'Not applicable.',
    database_feedback: 'Not applicable.',
    ai_ml_feedback: 'Not applicable.',
    hiring_note: 'Suitable for non-technical business role.',
    pipeline_stage: 'rejected',
    latest_stage_note: 'Closed for current technical opening.',
    submitted_at: '2026-06-09T04:15:00.000Z',
    processed_at: '2026-06-09T04:40:00.000Z',
    pipeline_stage_updated_at: '2026-06-13T11:00:00.000Z',
    city: 'Mumbai',
  },
  {
    candidate_name: 'Vikram Joshi',
    email: 'vikram.joshi.seed@hireflow.test',
    phone: '+91 9876500011',
    source: 'email',
    position: 'Mobile Engineer',
    years_of_exp: 4,
    linkedin: 'linkedin.com/in/vikramjoshi',
    current_job_title: 'Android Developer',
    highest_degree: 'B.Tech Computer Engineering',
    certifications: 'Kotlin Coroutines',
    frontend_skills: 'React Native',
    frontend_level: 'intermediate',
    backend_skills: 'Firebase Functions',
    backend_level: 'beginner',
    database_skills: 'Firebase, SQLite',
    database_level: 'intermediate',
    ai_ml_skills: 'On-device ML',
    ai_ml_level: 'beginner',
    cloud_devops: 'Firebase',
    programming_langs: 'Kotlin, JavaScript',
    notable_projects: 'Fintech app rewrite, offline sync architecture',
    jd_title: 'Mobile Engineer',
    jd_company: 'HireFlow',
    total_score: 84,
    frontend_score: 18,
    backend_score: 9,
    database_score: 10,
    ai_ml_score: 4,
    exp_score: 10,
    soft_score: 5,
    grade: 'A',
    recommendation: 'Hire',
    is_qualified: true,
    summary: 'Strong mobile engineering candidate with good shipping history.',
    strengths: 'Mobile architecture|Offline handling|Product ownership',
    weaknesses: 'Backend depth is limited',
    frontend_feedback: 'Good React Native exposure and mobile UI craft.',
    backend_feedback: 'Basic cloud function support only.',
    database_feedback: 'Enough for mobile persistence.',
    ai_ml_feedback: 'Light ML usage only.',
    hiring_note: 'Good option if mobile role opens immediately.',
    pipeline_stage: 'shortlisted',
    latest_stage_note: 'Waiting for hiring manager review.',
    submitted_at: '2026-06-24T06:00:00.000Z',
    processed_at: '2026-06-24T06:20:00.000Z',
    pipeline_stage_updated_at: '2026-06-26T10:45:00.000Z',
    city: 'Bangalore',
  },
  {
    candidate_name: 'Isha Gupta',
    email: 'isha.gupta.seed@hireflow.test',
    phone: '+91 9876500012',
    source: 'form',
    position: 'HR Operations Associate',
    years_of_exp: 2,
    linkedin: 'linkedin.com/in/ishagupta',
    current_job_title: 'Recruiting Coordinator',
    highest_degree: 'BBA',
    certifications: 'Talent Operations Fundamentals',
    frontend_skills: 'N/A',
    frontend_level: 'beginner',
    backend_skills: 'N/A',
    backend_level: 'beginner',
    database_skills: 'Google Sheets',
    database_level: 'beginner',
    ai_ml_skills: 'N/A',
    ai_ml_level: 'beginner',
    cloud_devops: 'N/A',
    programming_langs: 'N/A',
    notable_projects: 'Interview scheduling automation',
    jd_title: 'HR Operations Associate',
    jd_company: 'HireFlow',
    total_score: 74,
    frontend_score: 0,
    backend_score: 0,
    database_score: 2,
    ai_ml_score: 0,
    exp_score: 10,
    soft_score: 5,
    grade: 'B',
    recommendation: 'Consider',
    is_qualified: true,
    summary: 'Useful operations profile for hiring coordination and scheduling workflows.',
    strengths: 'Coordination|Documentation|Recruiting process support',
    weaknesses: 'Not relevant for software hiring',
    frontend_feedback: 'Not applicable.',
    backend_feedback: 'Not applicable.',
    database_feedback: 'Basic operational data handling.',
    ai_ml_feedback: 'Not applicable.',
    hiring_note: 'Potential fit for HR operations pipeline.',
    pipeline_stage: 'screening',
    latest_stage_note: 'New profile awaiting ops review.',
    submitted_at: '2026-06-26T08:10:00.000Z',
    processed_at: '2026-06-26T08:30:00.000Z',
    pipeline_stage_updated_at: '2026-06-26T08:30:00.000Z',
    city: 'Delhi',
  },
];

async function main(): Promise<void> {
  const client = await pool.connect();

  try {
    await client.query('BEGIN');

    await client.query(
      `DELETE FROM candidate_stage_history
       WHERE candidate_id IN (
         SELECT id FROM candidates WHERE email LIKE '%@hireflow.test'
       )`,
    );

    await client.query(`DELETE FROM candidates WHERE email LIKE '%@hireflow.test'`);

    for (const candidate of candidates) {
      const insertRes = await client.query<{ id: number }>(
        `INSERT INTO candidates (
          submitted_at, processed_at, source,
          candidate_name, email, phone, position, years_of_exp,
          linkedin, current_job_title, highest_degree, certifications,
          frontend_skills, frontend_level,
          backend_skills, backend_level,
          database_skills, database_level,
          ai_ml_skills, ai_ml_level,
          cloud_devops, programming_langs, notable_projects,
          jd_title, jd_company,
          total_score, frontend_score, backend_score,
          database_score, ai_ml_score, exp_score, soft_score,
          grade, recommendation, is_qualified,
          summary, strengths, weaknesses,
          frontend_feedback, backend_feedback, database_feedback,
          ai_ml_feedback, hiring_note,
          pipeline_stage, pipeline_stage_updated_at, latest_stage_note,
          city
        ) VALUES (
          $1, $2, $3,
          $4, $5, $6, $7, $8,
          $9, $10, $11, $12,
          $13, $14,
          $15, $16,
          $17, $18,
          $19, $20,
          $21, $22, $23,
          $24, $25,
          $26, $27, $28,
          $29, $30, $31, $32,
          $33, $34, $35,
          $36, $37, $38,
          $39, $40, $41,
          $42, $43,
          $44, $45, $46, $47
        )
        RETURNING id`,
        [
          candidate.submitted_at,
          candidate.processed_at,
          candidate.source,
          candidate.candidate_name,
          candidate.email,
          candidate.phone,
          candidate.position,
          candidate.years_of_exp,
          candidate.linkedin,
          candidate.current_job_title,
          candidate.highest_degree,
          candidate.certifications,
          candidate.frontend_skills,
          candidate.frontend_level,
          candidate.backend_skills,
          candidate.backend_level,
          candidate.database_skills,
          candidate.database_level,
          candidate.ai_ml_skills,
          candidate.ai_ml_level,
          candidate.cloud_devops,
          candidate.programming_langs,
          candidate.notable_projects,
          candidate.jd_title,
          candidate.jd_company,
          candidate.total_score,
          candidate.frontend_score,
          candidate.backend_score,
          candidate.database_score,
          candidate.ai_ml_score,
          candidate.exp_score,
          candidate.soft_score,
          candidate.grade,
          candidate.recommendation,
          candidate.is_qualified,
          candidate.summary,
          candidate.strengths,
          candidate.weaknesses,
          candidate.frontend_feedback,
          candidate.backend_feedback,
          candidate.database_feedback,
          candidate.ai_ml_feedback,
          candidate.hiring_note,
          candidate.pipeline_stage,
          candidate.pipeline_stage_updated_at,
          candidate.latest_stage_note,
          candidate.city,
        ],
      );

      await client.query(
        `INSERT INTO candidate_stage_history (candidate_id, from_stage, to_stage, note, changed_at)
         VALUES ($1, $2, $3, $4, $5)`,
        [
          insertRes.rows[0].id,
          null,
          candidate.pipeline_stage,
          candidate.latest_stage_note,
          candidate.pipeline_stage_updated_at,
        ],
      );
    }

    await client.query('COMMIT');
    console.log(`Seeded ${candidates.length} dummy candidates.`);
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((error) => {
  console.error('Failed to seed dummy candidates:', error);
  process.exit(1);
});
